version: "3.9"

services:
    app:
        build:
            context: ../php-symfony
            target: development
        environment:
            - HOME=/tmp
            - APP_ENV=${APP_ENV:-dev}
        volumes:
            - "./:/srv/app:rw"
        user: "${UID}:${GID}"
        restart: unless-stopped
        ports:
            - "8081:80"
        networks:
            - default

networks:
    default: ~
