version: "3.9"

services:
    app:
        build:
            context: ../php-symfony
            target: development
            args:
                USER: "${DOCKER_UID:-1000}"
        environment:
            - HOME=/tmp
            - APP_ENV=${APP_ENV:-dev}
        volumes:
            - "./:/srv/app:rw"
        user: "${DOCKER_UID:-1000}"
        restart: unless-stopped
        ports:
            - "8082:80"
        networks:
            - default

networks:
    default: ~
