version: "3.9"

services:
  app:
    build:
      context: ../js-node-express
      target: development
      args:
        NODE_ENV: local
    environment:
      - HOME=/tmp
      - APP_ENV=${APP_ENV:-dev}
      - NODE_ENV=local
    volumes:
      - "./:/srv/app:rw"
    user: "${UID:GID}"
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - default

networks:
  default: ~
